### ISSUE TITLE
Replace usages of sequence-cell CSS class

### ISSUE THREAD

**Issue by igboyes** [virtool/virtool#1718]
#### `styles.less`
```css
td.sequence-cell {
    padding: 0 !important;
    font-family: "Roboto Mono", monospace;
}

td.sequence-cell > textarea {
    width: 100%;
    margin: 0 0 -4px 0;
    padding: 5px;
    border: none;
}
```
Replace usages of these rules with a styled component.
- [x] make styled component
- [x] remove LESS rules
