### ISSUE TITLE
Conda environment.yml for simple development env setup

### ISSUE THREAD

**Issue by peterk87** [virtool/virtool#1998]
It'd be nice to be able to install all dependencies, especially bioinformatics tools and software required by Virtool in one shot. Conda could help with this and would allow new tools to be easily added when needed. I already do this for my own Virtool dev env with Redis and Mongo running with docker-compose.

### Example environment.yml

`environment.yml`:

```yml
name: virtool@5.0.0
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # bioinformatics tools
  - aodp>=2.5.0.1  # TODO: make a Bioconda recipe for AODP so it isn't such a pain to install...
  - bowtie2>=2.3.2
  - fastqc>=0.11.8
  - flash=1.2.11
  - hmmer>=3.1b2
  - skewer=0.2.2
  - spades>=3.11.0
  # web app deps
  - nodejs>=15.3.0   # don't rely on outdated npm/nodejs in Ubuntu...
  # Python dependencies
  - python>=3.7
  - pip
  - pip:
    - virtool==5.0.0
    # other PyPI dependencies that may not be automatically pulled in with virtool package specified
```

### Usage

Just getting Virtool up and running:

```bash
wget https://github.com/virtool/virtool/raw/master/environment.yml
conda create -f environment.yml
conda activate virtool@5.0.0
# assuming that Mongo and Redis are already running and that entrypoint script for starting app is simply virtool
virtool
```

Getting a dev env up and running:

```bash
git clone https://github.com/virtool/virtool
cd virtool
conda create -f environment.yml
conda activate virtool@5.0.0
pushd client
npm install
yarn build # or "yarn start" in another terminal with conda env activated
popd
# pip install Python dependencies into virtool@5.0.0 Conda env
pip install -r requirements.txt
./run.py
# or with pip and setup.py
pip install -e .
virtool
```

In PyCharm, specify the `virtool@5.0.0` conda environment as Python Interpreter.
